### ISSUE TITLE
Weights file

### ISSUE THREAD

**Issue by skn123** [stes/fan#5]
Can you please provide access to the weights file listed in your Readme.md? When I try to run Demo.ipnb it complains about the file being missing.

**Comment by stes** [comment]
Hello @skn123 , sorry there likely was a mistake in wrapping up the files for the first release.
I uploaded the model weights used for running the Demo Notebook as a separate release.
Please find them here: https://github.com/stes/fan/releases/tag/0.0.2

In order to run the notebook as-is, download the model weights and put them into the `weights/` subfolder in the root directory of the repo. Alternatively, you might specify a different part when you load the model:

``` python
model = fan.NormalizationNetwork(fname='weights/171028-weights-dlmia.npz',
                                patch_size=1000,
                                batch_size=1)
```
